config/routes.rb
Rails.application.routes.draw do
  filter :locale
  root to: 'main#index'
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  
  resources :user_sessions, only: :create
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  match 'oauth/callback' => 'oauths#callback', via: [:get, :post]
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  scope module: 'dashboard' do
    resources :cards

    resources :blocks do
      member do
        post 'set_as_current'
        post 'reset_as_current'
      end
    end

    post 'review_card' => 'trainer#review_card'
    get 'trainer' => 'trainer#index'
  end
end

app/controllers/home/user_sessions_controller.rb
class Home::UserSessionsController < Home::BaseController
  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_path, notice: t(:log_in_is_successful_notice)
    else
      flash.now[:alert] = t(:not_logged_in_alert)
      render :new
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    if current_user
      redirect_to root_path
    else
      @user = User.new
    end
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to root_path, notice: t(:log_in_is_successful_notice)
    else
      flash.now[:alert] = t(:not_logged_in_alert)
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, notice: t(:log_out_is_successful_notice)
  end
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, method: :post do %>
  <div class="form-group">
    <%= label_tag t(:email_label) %><br />
    <%= text_field_tag :email, nil, class: 'form-control', required: true,
                       autofocus: true %>
  </div>
  <div class="form-group">
    <%= label_tag t(:password_label) %><br />
    <%= password_field_tag :password, nil, class: 'form-control',
                           required: true %>
  </div>
  <%= submit_tag t(:log_in_label), class: 'btn btn-default' %>
<% end %>

app/views/user_sessions/new.html.erb
<h2><%= t(:sing_in_label) %></h2>

<%= render 'form', user: @user  %>